<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYytxonh\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYytxonh/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerYytxonh.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerYytxonh\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerYytxonh\appProdProjectContainer([
    'container.build_hash' => 'Yytxonh',
    'container.build_id' => 'ead20f4b',
    'container.build_time' => 1752680202,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYytxonh');
